GetGoing/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  root 'posts#index' # root page

  mount ActionCable.server => '/cable'

  # Authentication routes
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations',
                                    sessions: 'sessions',
                                    invitations: 'users/invitations' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :subscribers

  get 'home/show'

  resources :posts do
    resources :responses do
      member { patch :set_top }
    end
    resources :post_users, path: :users, module: :posts
    member { get :new_invitation }
    member { post :claim }
    member { patch :cancel_claim}
  end

  resources :responses, only: [] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :booking_links, only: [:index, :destroy] do
    member { patch :upvote }
    member { patch :downvote }
    member { patch :click_by_author }
    member { get :edit_affiliate_revenue }
    member { patch :update_affiliate_revenue }
  end

  scope '/manage' do
    resources :users, only: [:index] do
      member { patch :assign_as_admin }
      member { patch :assign_as_moderator }
      member { patch :assign_as_simple_user }
    end

    resources :booking_link_types
  end

  resources :users, only: [:show, :edit] do
    collection { get :tippa_question }
    collection { put :tippa }
  end

  resources :places, only: [:index, :destroy] do
    collection { post :add_place_to_user }
    member { patch :set_as_current_location }
    member { patch :set_as_hometown }
  end

  resources :post_steps, controller: 'posts/post_steps', only: [:update, :show, :index] do
    collection { post :cancel_steps }
  end

  get 'profile', to: 'users#profile'

  get '/top' => 'responses#top'

  get '/top_email' => 'responses#top_email'

  # get '/tippa' => 'users#tippa'

  get '/all_posts' => 'posts#all_posts'

  get 'edit', to: 'users#edit'

  get '/tippa_guide' => 'posts#tippa_guide'

  get '/show' => 'posts#show'

  get '/new_post_design' => 'posts#new_post_design'

  get 'upvote_link' => 'posts#show'

  devise_scope :user do
    get "/new_tippa" => "registrations#new_tippa"
  end
end

GetGoing/app/models/booking_link.rb
class BookingLink < ApplicationRecord
  belongs_to :post, touch: true # touch allows to track the latest activity on the post with updated_at
  belongs_to :response

  has_many :votes, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :activities, as: :actionable, dependent: :destroy

  belongs_to :booking_link_type

  monetize :affiliate_revenue_cents

  enum url_type: [:restaurant, :hotel, :airbnb, :rental, :activity, :flight, :tour, :attraction]
end

GetGoing/app/models/booking_link_type.rb
class BookingLinkType < ApplicationRecord
  has_many :booking_links, dependent: :destroy

  has_many :booking_link_types_posts, dependent: :destroy
  has_many :posts, through: :booking_link_types_posts
end

GetGoing/app/controllers/booking_links_controller.rb
class BookingLinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking_link, only: [:upvote, :downvote, :destroy, :click_by_author, :edit_affiliate_revenue, :update_affiliate_revenue]
  before_action :set_post, only: [:upvote, :downvote, :destroy, :click_by_author]
  before_action :set_booking_links_service, only: [:upvote, :downvote, :destroy, :click_by_author]
  before_action :set_bl_voting_service, only: [:upvote, :downvote]

  def index
    @booking_links = sorted_and_paginated_booking_links
    authorize @booking_links
    @booking_links = @booking_links.decorate
  end

  def click_by_author
    authorize @booking_link
    head :ok if @booking_links_service.click_by_author
  end


  def edit_affiliate_revenue
    authorize @booking_link
    @booking_link = @booking_link.decorate
    respond_to :js
  end

  def update_affiliate_revenue
    authorize @booking_link
    affiliate_revenue_cents = params[:booking_link][:affiliate_revenue_cents].gsub(/[^0-9]/, '')
    if @booking_link.update(affiliate_revenue_cents: affiliate_revenue_cents)
      @booking_links = sorted_and_paginated_booking_links.decorate
      respond_to :js
    end
  end

  def upvote
    authorize @booking_link
    @bl_voting_service.upvote
    NotificationService.new(actor: current_user,
                            notifiable: @booking_link,
                            recipient: @booking_link.response.user).recommended_link_upvoted
    PostsMailer.upvoted_link(@post, current_user, @booking_link.response.user, @booking_link).deliver_later
    set_structured_booking_links
    respond_to :js
  end

  def downvote
    authorize @booking_link
    @bl_voting_service.downvote
    set_structured_booking_links
    respond_to :js # 'Remove the link?' modal will still appear even if the link was already downvoted earlier and downvoting is ignored now
  end

  def destroy
    authorize @booking_link
    if @booking_link.destroy
      UserScoreService.new(user: @booking_link.response.user).update_score('remove')
    end
    set_structured_booking_links
    respond_to :js
  end

  private

  def set_booking_link
    @booking_link = BookingLink.find(params[:id])
  end

  def set_bl_voting_service
    @bl_voting_service = BookingLinkVotingService.new(user: current_user,
                                                      booking_link: @booking_link)
  end

  def set_post
    @post = @booking_link.post
  end

  def set_booking_links_service
    @booking_links_service = BookingLinksService.new(post: @post, booking_link: @booking_link)
  end

  def set_structured_booking_links
    @structured_booking_links = @booking_links_service.structured_booking_links
  end

  def sorted_and_paginated_booking_links
    BookingLink.all.order(created_at: :desc).paginate(page: params[:page], per_page: 30)
  end
end

GetGoing/app/views/booking_links/_booking_link.html.erb
<div class="booking_links_post">
  <% if policy(booking_link).downvote? %>
    <%= booking_link.downvotes_count %>
    <%= link_to downvote_booking_link_path(booking_link), remote: true, method: :patch, class: 'clear_link' do %>
      <%= icon "thumbs-down" %>
    <% end %>
  <% else %>
    <%= booking_link.downvotes_count %>
    <%= icon "thumbs-down" %>
  <% end %>

  <% if policy(booking_link).track_click? %>
    <%= link_to truncate(booking_link.url_title, length: 40), booking_link.url, target: :_blank, :'data-trackable' => booking_link.id %>
  <% else %>
    <%= link_to truncate(booking_link.url_title, length: 40), booking_link.url, target: :_blank%>
  <% end %>

  <div class='right-block'>
    <% if policy(booking_link).upvote? %>
      <%= booking_link.upvotes_count %>
      <%= link_to upvote_booking_link_path(booking_link), remote: true, method: :patch, class: 'clear_link' do %>
        <%= icon "thumbs-up" %>
      <% end %>
  <% else %>
      <%= booking_link.upvotes_count %>
      <%= icon "thumbs-up" %>
  <% end %>
</div>
</div>

GetGoing/app/views/booking_links/_booking_links.html.erb
<div class="post-links-div">
  <h1 class="posts-heading">Booking Links</h1>

  <% @structured_booking_links.each do |url_type_name, booking_links| %>
    <h3 class="post-link-headings"><%=url_type_name%></h3>
    <% booking_links.each do |booking_link| %>
      <%= render partial: 'booking_links/booking_link', locals: { booking_link: booking_link } %>
    <%end%>
  <% end %>
</div>

GetGoing/app/views/booking_links/_booking_links_table.html.erb
<table class='table table-striped table-bordered table-hover'
  <thead>
    <tr>
      <th> Booking Link </th>
      <th> User </th>
      <th> Post </th>
      <th> Clicked by author?</th>
      <th> Affiliate Revenue Generated </th>
    </tr>
  </thead>
  <tbody>
    <% @booking_links.each do |booking_link| %>
      <tr>
        <td>
          <%= link_to truncate(booking_link.url_title, length: 40), booking_link.url, target: :_blank%>
        </td>
        <td>
          <%= "#{booking_link.response.user.first_name} #{booking_link.response.user.last_name}" %>
        </td>
        <td>
          <%= link_to booking_link.post.title, booking_link.post %>
        </td>
        <td>
          <center>
            <%= booking_link.clicked_by_author_at_display %>
          </center>
        </td>
        <td>
          <center>
            <%= humanized_money_with_symbol booking_link.affiliate_revenue %>
            <%= link_to edit_affiliate_revenue_booking_link_path(booking_link), remote: true, class: 'clear_link', title: 'Click here to edit affiliate revenue value' do %>
              <%= icon "pencil", title: 'Click here to edit affiliate revenue value' %>
            <% end %>
          </center>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<center>
  <%= will_paginate @booking_links %>
</center>

GetGoing/app/views/booking_links/_downvote.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <center>
        <h3>Would you like to remove the link?</h3>
      </center>
    </div>
    <!-- <div class="modal-body">
    </div> -->
    <div class="modal-footer">
      <%= link_to "Remove the link", booking_link_path(booking_link), remote: true, method: :delete, class: "btn btn-danger btn-ok" %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Just downvote</button>
    </div>
  </div>
</div>

GetGoing/app/views/booking_links/_edit_affiliate_revenue.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <center>
        <h3>Affiliate Revenue</h3>
      </center>
    </div>
    <%= form_for @booking_link, url: update_affiliate_revenue_booking_link_path, remote: true, method: :patch do |f| %>
      <div class="modal-body">
        <div class='form-group'>
          <div class='col-sm-2'>
            <%= f.label :affiliate_revenue_cents, 'Affiliate Revenue Value', class: "col-sm-2 control-label" %>
          </div>
          <div class='col-sm-8'>
            <%= f.text_field :affiliate_revenue_cents, value: (humanized_money @booking_link.affiliate_revenue), class: 'form-control', id: 'affiliate_revenue-input' %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit 'Save', class: "btn btn-info" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    <% end %>

  </div>
</div>

GetGoing/app/views/booking_links/_save.js.erb
$("#modal-component").modal("hide");
$("#booking_links_table").html("<%= escape_javascript(render(partial: 'booking_links/booking_links_table', locals: { booking_links: @booking_links })).html_safe %>");

GetGoing/app/views/booking_links/destroy.js.erb
$("#modal-component").modal("hide");
$("#booking_links").html("<%= escape_javascript(render(partial: 'booking_links/booking_links', locals: { booking_links: @post.booking_links })).html_safe %>");

GetGoing/app/views/booking_links/downvote.js.erb
$("#modal-component").html("<%= escape_javascript(render( partial: 'booking_links/downvote', locals: { :booking_link => @booking_link })).html_safe %>");
$("#modal-component").modal("show");
$("#booking_links").html("<%= escape_javascript(render(partial: 'booking_links/booking_links', locals: { booking_links: @structured_booking_links })).html_safe %>");

GetGoing/app/views/booking_links/edit_affiliate_revenue.js.erb
$("#modal-component").html("<%= escape_javascript(render( partial: 'booking_links/edit_affiliate_revenue', locals: { :booking_link => @booking_link })).html_safe %>");
$("#modal-component").modal("show");
$("#affiliate_revenue-input").inputmask("currency");

GetGoing/app/views/booking_links/index.html.erb
<br>
<div class='w-container'>
  <br>
  <div class='table-responsive' id='booking_links_table'>
    <%= render partial: 'booking_links/booking_links_table', locals: { booking_links: @booking_links } %>
  </div>
  <div id='modal-component' class="modal fade">
  </div>
</div>

GetGoing/app/views/booking_links/update_affiliate_revenue.js.erb
<%= render "save" %>

GetGoing/app/views/booking_links/upvote.js.erb
$("#booking_links").html("<%= escape_javascript(render(partial: 'booking_links/booking_links', locals: { booking_links: @structured_booking_links })).html_safe %>");