GetGoing/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  root 'posts#index' # root page

  mount ActionCable.server => '/cable'

  # Authentication routes
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations',
                                    sessions: 'sessions',
                                    invitations: 'users/invitations' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :subscribers

  get 'home/show'

  resources :posts do
    resources :responses do
      member { patch :set_top }
    end
    resources :post_users, path: :users, module: :posts
    member { get :new_invitation }
    member { post :claim }
    member { patch :cancel_claim}
  end

  resources :responses, only: [] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :booking_links, only: [:index, :destroy] do
    member { patch :upvote }
    member { patch :downvote }
    member { patch :click_by_author }
    member { get :edit_affiliate_revenue }
    member { patch :update_affiliate_revenue }
  end

  scope '/manage' do
    resources :users, only: [:index] do
      member { patch :assign_as_admin }
      member { patch :assign_as_moderator }
      member { patch :assign_as_simple_user }
    end

    resources :booking_link_types
  end

  resources :users, only: [:show, :edit] do
    collection { get :tippa_question }
    collection { put :tippa }
  end

  resources :places, only: [:index, :destroy] do
    collection { post :add_place_to_user }
    member { patch :set_as_current_location }
    member { patch :set_as_hometown }
  end

  resources :post_steps, controller: 'posts/post_steps', only: [:update, :show, :index] do
    collection { post :cancel_steps }
  end

  get 'profile', to: 'users#profile'

  get '/top' => 'responses#top'

  get '/top_email' => 'responses#top_email'

  # get '/tippa' => 'users#tippa'

  get '/all_posts' => 'posts#all_posts'

  get 'edit', to: 'users#edit'

  get '/tippa_guide' => 'posts#tippa_guide'

  get '/show' => 'posts#show'

  get '/new_post_design' => 'posts#new_post_design'

  get 'upvote_link' => 'posts#show'

  devise_scope :user do
    get "/new_tippa" => "registrations#new_tippa"
  end
end

GetGoing/app/controllers/booking_link_types_controller.rb
class BookingLinkTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking_link_type, only: [:edit, :update, :destroy]

  def index
    @booking_link_types = BookingLinkType.all
    authorize @booking_link_types
  end

  def new
    @booking_link_type = BookingLinkType.new
    authorize @booking_link_type
    respond_to :js
  end

  def create
    @booking_link_type = BookingLinkType.new(booking_link_type_params)
    authorize @booking_link_type
    @booking_link_type.save
    @booking_link_types = BookingLinkType.all
    respond_to :js
  end

  def edit
    authorize @booking_link_type
    respond_to :js
  end

  def update
    authorize @booking_link_type
    @booking_link_type.update(booking_link_type_params)
    @booking_link_types = BookingLinkType.all
    respond_to :js
  end

  def destroy
    authorize @booking_link_type
    @booking_link_type.destroy
    @booking_link_types = BookingLinkType.all
    respond_to :js
  end

  private

  def booking_link_type_params
    params.require(:booking_link_type).permit(:name, :url_type, :is_accommodation)
  end

  def set_booking_link_type
    @booking_link_type = BookingLinkType.find(params[:id])
  end
end

GetGoing/app/views/booking_link_types/_booking_link_types_table.html.erb
<table class='table table-striped table-bordered table-hover'
  <thead>
    <tr>
      <th> BookingLink Type </th>
      <th> Url Type (hashtag) </th>
      <th> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @booking_link_types.each do |booking_link_type| %>
      <tr>
        <td>
          <%= booking_link_type.name %>
        </td>
        <td>
          <%= booking_link_type.url_type %>
        </td>
        <td>
          <% if policy(booking_link_type).update? %>
            <%= link_to edit_booking_link_type_path(booking_link_type), remote: true, class: 'clear_link', title: 'Click here to edit booking link type' do %>
              <%= icon "pencil", title: 'Click here to edit booking link type' %>
            <% end %>
          <% end %>
          <% if policy(booking_link_type).destroy? %>
            <%= link_to booking_link_type, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'clear_link', title: 'Click here to remove booking link type' do %>
              <%= icon "times", title: 'Click here to remove booking link type' %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

GetGoing/app/views/booking_link_types/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <center>
        <h3>Edit booking link type</h3>
      </center>
    </div>
    <%= render partial: 'form' %>
  </div>
</div>

GetGoing/app/views/booking_link_types/_form.html.erb
<%= form_for @booking_link_type, remote: true do |f| %>
<div class="modal-body">
  <div class='form-group'>
    <%= f.label :name, 'Name (will be displayed on the booking links block in the Post page, e.g. Restaurant, Hotel...)' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :url_type, 'Url type name (hashtag). In order to work correctly, it should be lower case, one word in singular form. E.g. "hotel"' %>
    <%= f.text_field :url_type, class: 'form-control' %>
  </div>

  <div class="md-checkbox">
    <%= f.check_box :is_accommodation %>
    <%= f.label :is_accommodation  %>
  </div>

</div>
<div class="modal-footer">
  <%= f.submit 'Save', class: "btn btn-info" %>
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
</div>
<% end %>

GetGoing/app/views/booking_link_types/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <center>
        <h3>New booking link type</h3>
      </center>
    </div>
    <%= render partial: 'form' %>
  </div>
</div>

GetGoing/app/views/booking_link_types/_save.js.erb
$("#modal-component").modal("hide");
$("#booking_link_types_table").html("<%= escape_javascript(render(partial: 'booking_link_types/booking_link_types_table', locals: { booking_link_types: @booking_link_types })).html_safe %>");

GetGoing/app/views/booking_link_types/create.js.erb
<%= render "save" %>

GetGoing/app/views/booking_link_types/destroy.js.erb
<%= render "save" %>

GetGoing/app/views/booking_link_types/edit.js.erb
$("#modal-component").html("<%= escape_javascript(render( partial: 'booking_link_types/new', locals: { :booking_link_type => @booking_link_type })).html_safe %>");
$("#modal-component").modal("show");

GetGoing/app/views/booking_link_types/index.html.erb
<br>
<div class='w-container'>
  <% if policy(BookingLinkType).create? %>
    <%= link_to 'Create new Booking Link Type', new_booking_link_type_path, remote: true, class: 'btn btn-default' %>
    <br>
  <% end %>
  <br>
  <div class='table-responsive' id='booking_link_types_table'>
    <%= render partial: 'booking_link_types/booking_link_types_table', locals: { booking_link_types: @booking_link_types } %>
  </div>
  <div id='modal-component' class="modal fade">
  </div>
</div>

GetGoing/app/views/booking_link_types/new.js.erb
$("#modal-component").html("<%= escape_javascript(render( partial: 'booking_link_types/new', locals: { :booking_link_type => @booking_link_type })).html_safe %>");
$("#modal-component").modal("show");

GetGoing/app/views/booking_link_types/update.js.erb
<%= render "save" %>