GetGoing/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  root 'posts#index' # root page

  mount ActionCable.server => '/cable'

  # Authentication routes
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations',
                                    sessions: 'sessions',
                                    invitations: 'users/invitations' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :subscribers

  get 'home/show'

  resources :posts do
    resources :responses do
      member { patch :set_top }
    end
    resources :post_users, path: :users, module: :posts
    member { get :new_invitation }
    member { post :claim }
    member { patch :cancel_claim}
  end

  resources :responses, only: [] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :booking_links, only: [:index, :destroy] do
    member { patch :upvote }
    member { patch :downvote }
    member { patch :click_by_author }
    member { get :edit_affiliate_revenue }
    member { patch :update_affiliate_revenue }
  end

  scope '/manage' do
    resources :users, only: [:index] do
      member { patch :assign_as_admin }
      member { patch :assign_as_moderator }
      member { patch :assign_as_simple_user }
    end

    resources :booking_link_types
  end

  resources :users, only: [:show, :edit] do
    collection { get :tippa_question }
    collection { put :tippa }
  end

  resources :places, only: [:index, :destroy] do
    collection { post :add_place_to_user }
    member { patch :set_as_current_location }
    member { patch :set_as_hometown }
  end

  resources :post_steps, controller: 'posts/post_steps', only: [:update, :show, :index] do
    collection { post :cancel_steps }
  end

  get 'profile', to: 'users#profile'

  get '/top' => 'responses#top'

  get '/top_email' => 'responses#top_email'

  # get '/tippa' => 'users#tippa'

  get '/all_posts' => 'posts#all_posts'

  get 'edit', to: 'users#edit'

  get '/tippa_guide' => 'posts#tippa_guide'

  get '/show' => 'posts#show'

  get '/new_post_design' => 'posts#new_post_design'

  get 'upvote_link' => 'posts#show'

  devise_scope :user do
    get "/new_tippa" => "registrations#new_tippa"
  end
end

GetGoing/app/models/post.rb
class Post < ApplicationRecord
  # belongs_to :user
  has_many :booking_links, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :top_responses
  has_many :claims, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :activities, as: :actionable, dependent: :destroy

  has_many :post_users, dependent: :destroy
  has_many :users, through: :post_users

  has_many :place_post_relations, dependent: :destroy
  has_many :places, through: :place_post_relations

  has_many :booking_link_types_posts, dependent: :destroy
  has_many :booking_link_types, through: :booking_link_types_posts

  has_secure_token :invitation_token

  accepts_nested_attributes_for :places
  attr_accessor :main_destinataion_city
  attr_accessor :main_destinataion_country

  after_save :set_closing_job

  # serialize :claimed_users, Array

  validates_presence_of :title

  def owner
    User.where(id: post_users.ownerships.pluck(:user_id)).first
  end

  def invited_users
    User.where(id: post_users.invitations.pluck(:user_id))
  end

  def owner=(user)
    post_users.create(user: user, role: 'owner') unless owner?(user)
  end

  def owner?(user)
    post_users.where(user: user).where(role: 'owner').present?
  end

  def invite_user(user)
    post_users.create(user: user, role: 'invited_user') unless invited?(user)
  end

  def invited?(user)
    post_users.where(user: user).where(role: 'invited_user').present?
  end

  scope :status_open, -> { where(status: true).order(created_at: :desc) }
  scope :new_posts, -> { where('created_at >= ?', 1.day.ago).order(created_at: :desc)  }

  searchkick # index model with elasticsearch

  def search_data
    {
      title: title,
      who_is_traveling: who_is_traveling,
      body: body,
      budget: budget,
      destination: destination,
      structured: structured,
      already_booked: already_booked,
      places_city: places.map(&:city),
      places_country: places.map(&:country),
      places_state: places.map(&:state)
    }
  end

  def status_open?
    status
  end

  def close
    self.status = false
    save
  end

  def set_closing_job
    ClosePostByDeadlineJob.set(wait_until: expired_at + 22.hours + 25.minutes).perform_later(self) if expired_at.present?
  end
end

GetGoing/app/controllers/posts/post_steps_controller.rb
class Posts::PostStepsController < ApplicationController
  include Wicked::Wizard

  steps :main_place, :welcome, :destinations, :who_is_traveling, :people_total,
        :travel_dates, :recommendations, :accommodations, :travel_style, :budget,
        :post_body

  def show
    wizard_steps_service = WizardStepsService.new
    case step
    when :welcome
      remote_step_render(:welcome) if initialize_welcome
    when :destinations
      remote_step_render(:destinations) if initialize_destinations
    when :who_is_traveling
      remote_step_render(:who_is_traveling) if initialize_who_is_traveling
    when :people_total
      if wizard_steps_service.ask_total_people?(session[:post][:who_is_traveling])
        remote_step_render(:people_total) if initialize_people_total
      else
        remote_step_render(:who_is_traveling) if initialize_who_is_traveling
      end
    when :travel_dates
      remote_step_render(:travel_dates) if initialize_travel_dates
    when :recommendations
      remote_step_render(:recommendations) if initialize_recommendations
    when :accommodations
      if wizard_steps_service.ask_accommodations?(session[:post][:booking_link_type_ids])
        remote_step_render(:accommodations) if initialize_accommodations
      else
        remote_step_render(:recommendations) if initialize_recommendations
      end
    when :travel_style
      remote_step_render(:travel_style) if initialize_travel_style
    when :budget
      remote_step_render(:budget) if initialize_budget
    when :post_body
      remote_step_render(:post_body) if initialize_post_body
    end
  end

  def update
    wizard_steps_service = WizardStepsService.new
    case step
    when :main_place
      session[:post] = {}
      remote_step_render(:welcome) if perform_main_place
    when :destinations
      remote_step_render(:who_is_traveling) if perfrom_destionations
    when :who_is_traveling
      if wizard_steps_service.ask_total_people?(post_params[:who_is_traveling])
        remote_step_render(:people_total) if perfrom_who_is_traveling
      else
        remote_step_render(:travel_dates) if perfrom_who_is_traveling && initialize_travel_dates
      end
    when :people_total
      remote_step_render(:travel_dates) if perform_people_total
    when :travel_dates
      remote_step_render(:recommendations) if perfrom_travel_dates
      # session[:post] = session[:post].merge(post_params)
      # @post = Post.new(session[:post])
      # @post.owner = current_user if current_user.present?
      # @post.save
      # redirect_to post_path(@post)
    when :recommendations
      if wizard_steps_service.ask_accommodations?(post_params[:booking_link_type_ids])
        remote_step_render(:accommodations) if perfrom_recommendations
      else
        remote_step_render(:travel_style) if perfrom_recommendations && perfrom_travel_style
      end

    when :accommodations
      remote_step_render(:travel_style) if perfrom_accommodations
    when :travel_style
      remote_step_render(:budget) if perfrom_travel_style
    when :budget
      remote_step_render(:post_body) if perfrom_budget
    when :post_body
      perform_post_body
      if current_user.present?
        @post = PostSavingService.new(user: current_user, session: session).save_post
        finish_wizard
      else
        render_registration
      end
    end
  end

  def finish_wizard
    render :finish_wizard, format: :js,
                      locals: { redirect_url: post_path(@post) }
  end

  def render_registration
    render 'devise/registrations/new', format: :js,
                      locals: { }
  end

  def cancel_steps
    WizardStepsService.new(session: session).clear_new_post_wizard
    respond_to :js
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :who_is_traveling, :main_destinataion_city,
                                 :main_destinataion_country, :who_is_traveling_other,
                                 :travel_start, :travel_end, { booking_link_type_ids: []},
                                 { amenities: [] }, { accomodation_style: []},
                                 :traveler_rating, :location_distance, :location_from,
                                 :min_accomodation_price, :max_accomodation_price,
                                 :neighborhoods,
                                 :travel_style, :budget, :people_total,
                                 places_attributes: %i[city google_place_id
                                                       state country latitude
                                                       longitude _destroy])
  end

  def perform_main_place
    initialize_welcome
  end

  def initialize_welcome
    if params[:post].present? && post_params[:places_attributes]['0'][:google_place_id].present?
      @place = Place.new(post_params[:places_attributes]['0'])
      set_initial_place
    elsif session[:post][:main_place].present?
      @place = Place.new(session[:post][:main_place])
      set_initial_place
    else
      false
    end
  end

  def set_initial_place
    if @place.city.present?
      @place.place_type = 'city'
    elsif @place.state.present?
      @place.place_type = 'region'
    elsif @place.country.present?
      @place.place_type = 'country'
    end
    @post = Post.new
    session[:post][:main_place] = @place.attributes
    @place = @place.decorate
  end

  def perfrom_destionations
    if post_params[:places_attributes].present?
      session[:post][:places] = post_params[:places_attributes]
      @post = Post.new
      initialize_who_is_traveling
    end
  end

  def initialize_destinations
    @places = []
    @post = Post.new
    if session[:post][:places].present?
      # @places = session[:places]
      session[:post][:places].keys.each do |place_id|
        next if session[:post][:places][place_id]['_destroy'] == '1'
        session[:post][:places][place_id].delete('_destroy')
        @places << Place.new(session[:post][:places][place_id]) if session[:post][:places][place_id][:google_place_id].present?
      end
    else
      @places << Place.new(session[:post][:main_place])
    end
  end

  def perfrom_who_is_traveling
    if post_params[:who_is_traveling] == PostOptions.who_is_traveling(:other)
      session[:post][:who_is_traveling] = post_params[:who_is_traveling_other]
    else
      session[:post][:who_is_traveling] = post_params[:who_is_traveling]
    end
    initialize_people_total
  end

  def initialize_who_is_traveling
    @post = Post.new
    if session[:post][:who_is_traveling].present? && PostOptions.traveling_other?(session[:post][:who_is_traveling])
      @who_is_traveling_other = session[:post][:who_is_traveling]
      @post.who_is_traveling = PostOptions.who_is_traveling(:other)
    elsif session[:post][:who_is_traveling].present?
      @post.who_is_traveling = session[:post][:who_is_traveling]
      @who_is_traveling_other = ''
    end
    true
  end

  def initialize_people_total
    @post = Post.new
    @post.people_total = session[:post][:people_total]
    true
  end

  def perform_people_total
    session[:post][:people_total] = post_params[:people_total]
    initialize_travel_dates
  end

  def perfrom_travel_dates
    session[:post][:travel_start] = post_params[:travel_start] if post_params[:travel_start].present?
    session[:post][:travel_end] = post_params[:travel_end]   if post_params[:travel_end].present?
    initialize_recommendations
  end

  def initialize_travel_dates
    @post = Post.new
    @post.travel_start = session[:post][:travel_start] if session[:post][:travel_start].present?
    @post.travel_end = session[:post][:travel_end] if session[:post][:travel_end].present?
    @post
  end

  def perfrom_recommendations
    session[:post][:booking_link_type_ids] = post_params[:booking_link_type_ids] if post_params[:booking_link_type_ids].present?
    session[:post][:booking_link_type_ids]
    initialize_accommodations
  end

  def initialize_recommendations
    @post = Post.new
    @booking_link_type_ids = []
    if session[:post][:booking_link_type_ids].present?
      session[:post][:booking_link_type_ids].each do |link_type|
        blt = BookingLinkType.where(id: link_type).first
        @booking_link_type_ids << blt.id if blt.present?
      end
    end
    @booking_link_types = BookingLinkType.all
  end

  def perfrom_accommodations
    session[:post][:min_accomodation_price] = post_params[:min_accomodation_price]
    session[:post][:max_accomodation_price] = post_params[:max_accomodation_price]
    session[:post][:amenities] = post_params[:amenities]
    session[:post][:location_distance] = post_params[:location_distance]
    session[:post][:location_from] = post_params[:location_from]
    session[:post][:neighborhoods] = post_params[:neighborhoods]
    session[:post][:traveler_rating] = post_params[:traveler_rating]
    session[:post][:accomodation_style] = post_params[:accomodation_style]
    initialize_travel_style
  end

  def initialize_accommodations
    @post = Post.new
    @post.min_accomodation_price = session[:post][:min_accomodation_price]
    @post.max_accomodation_price = session[:post][:max_accomodation_price]
    @post.amenities = session[:post][:amenities] if session[:post][:amenities].present?
    @post.location_distance = session[:post][:location_distance]
    @post.location_from = session[:post][:location_from]
    @post.neighborhoods = session[:post][:neighborhoods]
    @post.traveler_rating = session[:post][:traveler_rating]
    @post.accomodation_style = session[:post][:accomodation_style] if session[:post][:accomodation_style].present?
    true
  end

  def initialize_travel_style
    @post = Post.new
    @post.travel_style = session[:post][:travel_style]
    true
  end

  def perfrom_travel_style
    session[:post][:travel_style] = post_params[:travel_style]
    initialize_budget
  end

  def initialize_budget
    @post = Post.new
    @post.budget = session[:post][:budget]

    true
  end

GetGoing/app/controllers/posts/post_users_controller.rb
# This controller handles users invitation to posts
class Posts::PostUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    emails = extract_emails_to_array(post_users_params[:email]) if post_users_params[:email].present?
    invitation_status = 'Invitation has not been sent, please make sure entered correct email address'
    if emails.present?
      emails.each do |email|
        if email == current_user.email
          invitation_status = 'You already own thit Post, instead you can invite your friends to join.'
        else
          invite_user(email)
          invitation_status = 'Thank you! Your invitation has been successfully sent' if User.where(email: email).present?
        end
      end
    end
    render 'posts/invitation_sent', format: :js, locals: { invitation_status: invitation_status }
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def post_users_params
    params.require(:post_user).permit(:email)
  end

  def invite_user(email)
    post_user = PostUser.new(email: email, role: 'invited_user', post: @post)
    authorize post_user
    post_user.save
    post_user.user.notify_existing_about_invitation if post_user.user.invitation_token.blank?
  end

  def extract_emails_to_array(emails)
    reg = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
    emails.scan(reg).uniq
  end
end

GetGoing/app/helpers/posts_helper.rb
module PostsHelper
  def current_status(post)
    return 'open' if post.status
    'closed'
  end
end

GetGoing/app/views/posts/_apply_claim.js.erb
$("#claim-block").html("<%= escape_javascript(render(partial: 'claim')).html_safe %>");
$("#new-responses").html("<%= escape_javascript(render(partial: 'responses/new')).html_safe %>");
<% flash.each do |type, message| %>
  $("#flash-messages").append("<%= j content_tag :p, message.html_safe, class: "flash text-center" %>").hide().fadeIn(1000);
<% end %>

GetGoing/app/views/posts/_claim.html.erb
<div id='flash-messages'></div>
<% if policy(@post).claim? %>
  <%= link_to "Respond to this Post", claim_post_path(@post), method: :post, remote: true, class: 'btn btn-default app_nav' %>
<% elsif policy(@post).cancel_claim? %>
  <div class="app_nav"><br>You've claimed this post</br></div>
  <%= link_to "Click Here to Cancel Your Claim", cancel_claim_post_path(@post), method: :patch, remote: true, class: 'btn btn-default app_nav' %>
  <br></br>
<% elsif policy(@post).waitlisted? %>
  <div class="app_nav"><br>You've been waitlisted to claim this post.</br></div>
  <%= link_to "Click Here to Cancel Your Claim Requst", cancel_claim_post_path(@post), method: :patch, remote: true, class: 'btn btn-default app_nav' %>
  <br></br>
<% end %>

GetGoing/app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <div class="section-2">
    <div class="w-container">
      <div>
        <div class="w-row">
          <div class="w-clearfix w-col w-col-6">
            <div class="user-profile-all-posts"><%= image_tag post.owner.picture_url, class: "posts-table-profile-image" %></img>
              <div class="text-block-14"><%= post.owner.first_name  %></div>
            </div>
            <div class="div-block-9 w-clearfix">
              <div class="posts-title-all-posts-table"><%= post.title %></div>
              <div class="post-body-all-posts-table"><%= truncate(post.body, length: 100) %></div>
            </div>
          </div>
          <div class="w-col w-col-2">
            <h4 class="posts-table-all-other-columns">
              <% post.places.each do |place| %>
                <%= icon "globe" %>
                <span class='place-name'><%= place.full_name %></span>
                <br>
              <% end %>
            </h4>
          </div>
          <div class="w-col w-col-1">
            <h4 class="posts-table-all-other-columns"><%= post.responses.count %></h4>
          </div>
          <div class="w-col w-col-2">
            <h4 class="posts-table-all-other-columns"><%= post.created_at %></h4>

          </div>
          <div class="w-col w-col-1">
            <h4 class="posts-table-all-other-columns"><%= current_status(post) %></h4>
          </div>
          <div class="control-post">
            <%= link_to "View Post", { controller: :posts, action: :show, id: post.id },{ class: 'view-post'} %>
            <% if policy(post).update? %>
              <%= link_to 'Edit Post', edit_post_path(post), class: 'view-post' %>
            <% end %>
            <% if policy(post).destroy? %>
              <%= link_to 'Remove Post', post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: 'view-post' %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

GetGoing/app/views/posts/cancel_claim.js.erb
<%= render "apply_claim" %>

GetGoing/app/views/posts/claim.js.erb
<%= render "apply_claim" %>

GetGoing/app/views/posts/index.html.erb
<%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?v=3.28&libraries=places&key=#{ENV['GOOGLE_MAPS_API']}" %>
<div id='modal-component' class="modal fade"></div>
<%= render partial: 'posts/post_steps/close_popup' %>
<div data-ix="new-interaction">
  <div class="navbar w-nav" data-animation="over-right" data-collapse="medium" data-duration="400">
    <div class="w-container">
      <a class="w-nav-brand" href="#">
        <%= image_tag "white_logo_transparent_background.png",  class: "logo-navbar", height: "70", width: "70" %>
      </a>
      <nav class="nav-menu w-nav-menu" role="navigation">
        <a class="nav-link w-nav-link" href="#How-It-Works">How It Works</a>
        <a class="nav-link w-nav-link" href="#Pricing-Secion">Pricing</a>
        <a class="nav-link w-nav-link" href="#Reviews">Reviews</a>
        <a class="nav-link w-nav-link" href="#">FAQ</a>
        <a class="nav-link w-nav-link">
          <% if user_signed_in? %>
          <%= link_to "Your Profile", user_path(current_user), class:"nav-link w-nav-link" %>
          <%= link_to "Log Out", destroy_user_session_path, :method => :delete, class:"nav-link w-nav-link" %>
          <div id='notifications-component' class="dropdown">
            <%= render partial: 'notifications/notifications_component' %>
          </div>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class:"w-nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"w-nav-link" %>
          <% end %></a>

        <div class="w-nav-button">
          <div class="nav-menu nav-menu-icon w-icon-nav-menu"></div>
        </div>
      </div>
    </div>
    <%= render 'layouts/messages' %>
    <div class="hero-section">
      <div class="heading-container w-container" data-ix="new-interaction">
        <h1 class="h1">Get travel recommendations and advice.</h1>
        <div class="hero-subheading">Personalized insights and links to help make planning and booking your trip a breeze.</div>
        <div class="div-block-14">
          <div class="w-form">
            <!-- <form class="form-2" data-name="Email Form 2" id="email-form-2" name="email-form-2"> -->
            <div class="w-clearfix place-form">
              <!-- <a class="button-6 w-button" href="#">&gt;</a> -->
              <%= form_for @post, url: post_steps_path+'/main_place', method: :put, remote: true, class: 'form-2' do |f| %>
              <!-- <input class="text-field-4 w-input" id="field" maxlength="256" name="field" placeholder="Where are you traveling?" required="required" type="text"> -->
              <a class="city-button selected w-button" id='city-toggle' href="#">City</a>
              <a class="country-button w-button" id='country-toggle' href="#">Country/Region</a>
              <%= f.text_field :main_destinataion_city, class: "autocomplete-field autocomplete-city w-input", maxlength: "256", placeholder: "Where are you traveling?" %>
              <%= f.text_field :main_destinataion_country, class: "autocomplete-field autocomplete-country w-input", maxlength: "256", placeholder: "Where are you traveling?"%>
              <%= f.fields_for :places, Place.new do |place|%>
              <%= render 'posts/post_steps/primer_place_fields', f: place %>
              <% end %>
              <%= f.submit '&gt;'.html_safe, class: "button-6 w-button" %>
              <% end %>
              <!-- <%= link_to '&gt;'.html_safe, post_steps_path, remote: true, class: "button-6 w-button" %> -->
            </div>
            <!-- </form> -->
            <div class="w-form-done">
              <div>Thank you! Your submission has been received!</div>
            </div>
            <div class="w-form-fail">
              <div>Oops! Something went wrong while submitting the form</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <section class="main-section" id="How-It-Works">
      <div class="w-container">
        <h2 class="black">How It Works</h2>
        <div class="w-row">
          <div class="w-col w-col-4 w-col-medium-4">
            <div class="about-block" data-ix="new-interaction-2"><img class="about-image" data-ix="new-interaction-2" src="/assets/149307.svg">
              <h3>Answer a few questions</h3>
              <p class="about-paragraph">Tell us about your trip so we can deliver quality advice and relevant links.</p>
            </div>
          </div>
          <div class="w-col w-col-4 w-col-medium-4">
            <div class="about-block" data-ix="new-interaction-3"><img class="about-image" src="/assets/179672.svg">
              <h3>Get Travel Advice&nbsp;</h3>
              <p class="about-paragraph-2">Our advisors give you valuable insights and recommendations.</p>
            </div>
          </div>
          <div class="w-col w-col-4 w-col-medium-4">
            <div class="about-block" data-ix="new-interaction-4"><img class="about-image" src="/assets/263056.svg">
              <h3>Book Your Trip</h3>
              <p class="about-paragraph-3">Relevant links are organized for you, so all you have to do is click and book.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="main-section pink">
      <div class="w-container">
        <h2 class="white">Save Time &amp; Travel Better</h2>
      </div>
      <ul class="list w-list-unstyled"></ul>
      <div class="w-row">
        <div class="w-col w-col-4">
          <div class="save-time-block" data-ix="new-interaction-5">
            <strong>Spend less time researching</strong>. No more reading and analyzing posts, blogs, and reviews trying to plan the perfect trip.
            <br>
            <br>Get links to book the best flights, hotels/airbnb's, restaurants, and things to do so all you have to do is click and pay.</div>
        </div>
        <div class="column-2-mobile w-col w-col-4">
          <%= image_tag "160132.svg", class: "travel-image", "data-ix" => "new-interaction-5", height: "200", width: "200" %>
        </div>
        <div class="w-col w-col-4">
          <div class="quality-block" data-ix="new-interaction-5">
            <strong>Take the guess work out of traveling</strong>. Get quality insights tailored to your desire.
            <br>
            <br>
            <br>Receive advice from a diverse group of people, instead of relying on one or two sources to plan your trip.</div>
        </div>
      </div>
    </div>
    <div class="pricing-section" id="Pricing-Secion">
      <div class="w-container">
        <h2 class="white">Pricing</h2>
      </div>
      <ul class="list w-list-unstyled"></ul>
      <div class="w-container">
        <div class="pricing-block">
          <h1 class="pricing-header">Free</h1>
          <ul class="pricing-list w-list-unstyled">
            <li data-ix="new-interaction-6">6 responses amounting to a full itinerary</li>
            <li data-ix="new-interaction-6">Travel booking links for easy booking</li>
            <li data-ix="new-interaction-8">Save on flights and hotels</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="reviews-section" id="Reviews">
      <div class="w-container">
        <h2 class="black">Reviews</h2>
        <div class="testimonials-slider w-slider" data-animation="slide" data-duration="500" data-infinite="1">

          <br></br>
          <br></br>
          No Reviews Yet.

        </div>

      </div>
    </div>
  </div>
  <div class="blue reviews-section" id="Sign-Up-Now">
    <div class="w-container">
      <h2 class="white">Sign Up Now</h2>
      <div class="subheading-text">We're just getting started. Drop your email address to get updates from us.</div>
      <div class="form-wrapper w-form">
        <form class="form-wrapper w-clearfix" data-name="Email Form" id="email-form" name="email-form">
          <input class="text-field w-input" data-name="Email" id="email" maxlength="256" name="email" placeholder="Enter your email address" required="required" type="email">
          <input class="submit-button w-button" data-wait="Please wait..." type="submit" value="Submit">
        </form>

        <div class="w-form-done">
          <div>Thank you! Your submission has been received!</div>
        </div>
        <div class="w-form-fail">
          <div>Oops! Something went wrong while submitting the form</div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer reviews-section">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6"></div>
        <div class="w-clearfix w-col w-col-6">
          <a class="footer-link" href="#">Sign Up</a>
          <a class="footer-link" href="#">FAQ</a>
          <a class="footer-link" href="#">Reviews</a>
          <a class="footer-link" href="#">Pricing</a>
          <a class="footer-link" href="#">How It Works</a>
        </div>
      </div>
    </div>
  </div>
</div>

GetGoing/app/views/posts/new.html.erb
<!DOCTYPE html>
<!--  This site was created in Webflow. http://www.webflow.com -->
<!--  Last Published: Wed Mar 08 2017 02:01:02 GMT+0000 (UTC)  -->
<html data-wf-page="54f7bd5e04a195de6e5adf11" data-wf-site="54f7bd5e04a195de6e5adf0f">
<head>
  <meta charset="utf-8">
  <title>Kenny&#39;s Playground</title>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href="/assets/normalize.css" rel="stylesheet" type="text/css">
  <link href="/assets/webflow.css" rel="stylesheet" type="text/css">
  <link href="/assets/kennykandola89.webflow.css" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript">
    WebFont.load({
      google: {
        families: ["Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic","Montserrat:400,700","Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic","Oswald:300,400,700","Great Vibes:400","Bitter:400,700,400italic","PT Serif:400,400italic,700,700italic","Roboto:300,regular,500,700","Roboto Condensed:regular,700","Roboto Slab:300,regular"]
      }
    });
  </script>
  <script src="js/modernizr.js" type="text/javascript"></script>
  <link href="https://daks2k3a4ib2z.cloudfront.net/placeholder/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <link href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png" rel="apple-touch-icon">
</head>
<body>



<title>Create a Post</title>

<center><h1>New Post</h1></center>



<%= render 'form' %>

<%= link_to 'Back', posts_path %>