GetGoing/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  root 'posts#index' # root page

  mount ActionCable.server => '/cable'

  # Authentication routes
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks',
                                    registrations: 'registrations',
                                    sessions: 'sessions',
                                    invitations: 'users/invitations' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :subscribers

  get 'home/show'

  resources :posts do
    resources :responses do
      member { patch :set_top }
    end
    resources :post_users, path: :users, module: :posts
    member { get :new_invitation }
    member { post :claim }
    member { patch :cancel_claim}
  end

  resources :responses, only: [] do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end

  resources :booking_links, only: [:index, :destroy] do
    member { patch :upvote }
    member { patch :downvote }
    member { patch :click_by_author }
    member { get :edit_affiliate_revenue }
    member { patch :update_affiliate_revenue }
  end

  scope '/manage' do
    resources :users, only: [:index] do
      member { patch :assign_as_admin }
      member { patch :assign_as_moderator }
      member { patch :assign_as_simple_user }
    end

    resources :booking_link_types
  end

  resources :users, only: [:show, :edit] do
    collection { get :tippa_question }
    collection { put :tippa }
  end

  resources :places, only: [:index, :destroy] do
    collection { post :add_place_to_user }
    member { patch :set_as_current_location }
    member { patch :set_as_hometown }
  end

  resources :post_steps, controller: 'posts/post_steps', only: [:update, :show, :index] do
    collection { post :cancel_steps }
  end

  get 'profile', to: 'users#profile'

  get '/top' => 'responses#top'

  get '/top_email' => 'responses#top_email'

  # get '/tippa' => 'users#tippa'

  get '/all_posts' => 'posts#all_posts'

  get 'edit', to: 'users#edit'

  get '/tippa_guide' => 'posts#tippa_guide'

  get '/show' => 'posts#show'

  get '/new_post_design' => 'posts#new_post_design'

  get 'upvote_link' => 'posts#show'

  devise_scope :user do
    get "/new_tippa" => "registrations#new_tippa"
  end
end

GetGoing/app/views/layouts/_messages.html.erb
<% if flash[:alert].present? %>
  <div class="alert alert-alert">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= flash[:alert] %>
      </li>
    </ul>
  </div>
<% end %>

GetGoing/app/views/layouts/application.html.erb
<html data-wf-page="58b8c5261ab749a61f69b0db" data-wf-site="54f7bd5e04a195de6e5adf0f">
<head>
  <meta charset="utf-8">
  <title>PostsShow</title>
  <meta content="PostsShow" property="og:title">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta content="Webflow" name="generator">
  <link href="/assets/normalize.css" rel="stylesheet" type="text/css">
  <link href="/assets/webflow.css" rel="stylesheet" type="text/css">
  <link href="/assets/kennykandola89.webflow.css" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
  <script type="text/javascript">
      WebFont.load({
          google: {
              families: ["Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic","Montserrat:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic","Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic","Oswald:200,300,400,500,600,700","Great Vibes:400","Bitter:400,700,400italic","PT Serif:400,400italic,700,700italic","Roboto:300,regular,500,700","Roboto Condensed:regular,700","Roboto Slab:300,regular"]
          }
      });
  </script>
  <!-- <script src="js/modernizr.js" type="text/javascript"></script> -->
  <link href="https://daks2k3a4ib2z.cloudfront.net/placeholder/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <link href="https://daks2k3a4ib2z.cloudfront.net/img/webclip.png" rel="apple-touch-icon">
  <%= action_cable_meta_tag if user_signed_in? %>
  <%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <% unless (current_page?(posts_path) || current_page?(root_path))%>
    <div class="navbar-logged-in w-nav" data-animation="default" data-collapse="medium" data-duration="400">
      <div class="w-container">
        <a class="w-nav-brand" href="/posts">
          <%= image_tag "white_logo_transparent_background.png", class: "logo-navbar", width: "91" %>
        </a>
        <nav class="w-nav-menu" role="navigation">
          <%= link_to 'Home', root_path, class: "nav-link w-nav-link" %>
          <a class="nav-link w-nav-link" href="#">About</a>
          <a class="nav-link w-nav-link" href="#">Contact</a>
          <% if user_signed_in? %>
            <%= link_to("New Post", new_post_path,  :class => "nav-link w-nav-link") %>
          <% end %>
          <% if user_signed_in? && policy(:user).index? %>
            <%= link_to "All users", users_path, :class => "nav-link w-nav-link" %>
          <% end %>
          <% if user_signed_in? %>
            <div id='notifications-component' class="dropdown">
              <%= render partial: 'notifications/notifications_component' %>
            </div>
            <%= link_to "Your Profile", user_path(current_user), class:"nav-link w-nav-link" %>
            <%= link_to "Log Out", destroy_user_session_path, :method => :delete, class:"nav-link w-nav-link" %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class:"w-nav-link" %>
            <%= link_to "Sign Up", new_user_registration_path, class:"w-nav-link" %>
          <% end %>
          </a>
        </nav>
        <div class="w-nav-button">
          <div class="w-icon-nav-menu"></div>
        </div>
      </div>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>